apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratos
spec:
  destination:
    namespace: kratos
    server: https://kubernetes.default.svc
  project: default
  source:
    # There is no difference between dev and prod other than secrets,
    # and secrets are managed by terraform.
    path: ./kratos/base
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
