apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: kratos
spec:
  template:
    spec:
      containers:
        - name: kratos
          env:
            - name: COURIER_SMTP_FROM_ADDRESS
              value: "no-reply@login.beta.future.nhs.uk"
