apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
patchesJSON6902:
  - path: ingress-patch-host.yaml
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: ingress-service
patchesStrategicMerge:
  - ingress-patch-tls.yaml
  - cert-issuer-patch-env.yaml
