apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: hhttps://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    email: futurenhs-devs@red-badger.com
    solvers:
      - http01:
          ingress:
            class: nginx
