apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../prod/
patchesJSON6902:
  - path: patch-ingress-hello-world.yaml
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: ingress
      namespace: hello-world
patchesStrategicMerge:
  - patch-dns.yaml
