kind: ConfigMap # Documentation can be found here - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#configmap-file-settings-overview
apiVersion: v1
data:
  schema-version:
    v1
  config-version:
    ver1
  log-data-collection-settings: |-
    [log_collection_settings]
       [log_collection_settings.stdout]
          enabled = true 
          exclude_namespaces = ["kube-system"]
       [log_collection_settings.stderr]
          enabled = true
          exclude_namespaces = ["kube-system"]
       [log_collection_settings.env_var]
          enabled = true
       [log_collection_settings.enrich_container_logs]
          enabled = false
       [log_collection_settings.collect_all_kube_events]
          enabled = false
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
