apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
          - name: NEXT_PUBLIC_INSTRUMENTATION_KEY
            value: "todo: fill out after creating cluster"
