serve:
  public:
    base_url: /.ory/kratos/public/
    port: 4433
  admin:
    base_url: http://kratos:4434/
    port: 4434

selfservice:
  default_browser_return_url: /
  whitelisted_return_urls:
    - /

  strategies:
    password:
      enabled: true

  flows:
    settings:
      ui_url: /auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: /auth/recovery

    logout:
      after:
        default_browser_return_url: /auth/login

    login:
      ui_url: /auth/login
      request_lifespan: 10m

    registration:
      request_lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/identity.traits.schema.json

courier:
  smtp:
    # overridden by envrionment variable COURIER_SMTP_CONNECTION_URI which is
    # stored in sendgrid-sealed.yaml
    connection_uri: smtps://test:test@mailslurper.kratos:1025/?skip_ssl_verify=true
