serve:
  public:
    base_url: /.ory/kratos/public/
    port: 4433
  admin:
    base_url: http://kratos-public.kratos/
    port: 4434

selfservice:
  default_browser_return_url: /
  whitelisted_return_urls:
    - /
    - http://127.0.0.1:4455
    - http://127.0.0.1:3000
    - https://127.0.0.1:3000
    - https://fnhs.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-david.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-jan.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-matt.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-potts.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-tracy.westeurope.cloudapp.azure.com/
    - https://fnhs-dev-declan.westeurope.cloudapp.azure.com/

  strategies:
    password:
      enabled: true

  flows:
    error:
      ui_url: /error

    settings:
      ui_url: /settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: /recovery

    verification:
      enabled: true
      ui_url: /verify
      after:
        default_browser_return_url: /

    logout:
      after:
        default_browser_return_url: /auth/login

    login:
      ui_url: /auth/login
      request_lifespan: 10m

    registration:
      request_lifespan: 10m
      ui_url: /auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/identity.traits.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper.kratos:1025/?skip_ssl_verify=true
