apiVersion: v1
kind: Service
metadata:
  name: mailslurper
spec:
  type: ClusterIP
  selector:
    app: mailslurper
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 4437
      targetPort: smtp
      name: smtp
    - port: 1025
      targetPort: somethingelse
      name: somethingelse
