apiVersion: v1
kind: Service
metadata:
  name: mailslurper
spec:
  type: ClusterIP
  selector:
    app: mailslurper
  ports:
    - port: 80
      targetPort: 4436
    - port: 4437
      targetPort: 4437