serve:
  public:
    base_url: $KRATOS_WEB_ROOT/.ory/kratos/public/
    port: 4433
  admin:
    base_url: http://kratos:4434/
    port: 4434

selfservice:
  default_browser_return_url: $KRATOS_WEB_ROOT/
  whitelisted_return_urls:
    - $KRATOS_WEB_ROOT/

  strategies:
    password:
      enabled: true

  flows:
    error:
      ui_url: $KRATOS_WEB_ROOT/error

    settings:
      ui_url: $KRATOS_WEB_ROOT/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: $KRATOS_WEB_ROOT/recovery

    verification:
      enabled: true
      ui_url: $KRATOS_WEB_ROOT/verify
      after:
        default_browser_return_url: $KRATOS_WEB_ROOT/

    logout:
      after:
        default_browser_return_url: $KRATOS_WEB_ROOT/auth/login

    login:
      ui_url: $KRATOS_WEB_ROOT/auth/login
      request_lifespan: 10m

    registration:
      request_lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/identity.traits.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper.kratos:1025/?skip_ssl_verify=true
