apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: kratos
spec:
  template:
    spec:
      containers:
        - name: kratos
          env:
            - name: COURIER_SMTP_FROM_ADDRESS
              value: "no-reply@login.fnhs-dev-$NAME.westeurope.cloudapp.azure.com"
            - name: LOG_LEAK_SENSITIVE_VALUES
              value: "true"
            - name: SELFSERVICE_DEFAULT_BROWSER_RETURN_URL
              value: "/dev"
            - name: SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL
              value: "/dev?logged_out=yes_you_should_now_be_logged_out"
