apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-namespace.yaml
  - ingress-nginx.yaml
  - ingress.yaml
patchesStrategicMerge:
  - ingress-nginx-patch-replica.yaml
  - ingress-patch-dns.yaml
