version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  azure:
    image: mcr.microsoft.com/azure-storage/azurite:3.9.0
    restart: always
    ports:
      - 10000:10000 # blob storage
