apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./cert-manager
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      version: v1beta1
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/namespaceSelector/matchExpressions
