apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./frontend
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
