apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./ingress
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  # syncPolicy:
  #   automated:
  #     prune: true
