apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: ORIGIN
              value: https://beta.future.nhs.uk
            - name: WORKSPACE_SERVER_API_ROOT
              valueFrom:
                configMapKeyRef:
                  name: prod_config_map
                  key: workspace_server_api_root
