apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: hello-world
spec:
  tls:
    - hosts:
        - fnhs-dev-tracyw.westeurope.cloudapp.azure.com
      secretName: fnhs-dev-tracyw
