apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: hello-world
spec:
  tls:
    - hosts:
        - --DNS_PREFIX--.--REGION--.cloudapp.azure.com
      secretName: --DNS_PREFIX--

