apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
patchesStrategicMerge:
  - ingress-nginx-patch-replica.yaml
  - cert-issuer-patch-env.yaml
  - ingress-patch-dns.yaml
