apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
spec:
  template:
    spec:
      containers:
        - name: workspace
          env:
            - name: INSTRUMENTATION_KEY
              value: "$INSTRUMENTATION_KEY"
