apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favouritecuisine
  namespace: hello-world
spec:
  encryptedData:
    favouritecuisine: AgAX7YwuThwlvUN9nPKXEcTzT5RFsf0JSgKfbv+UhNl/f6LErolkFRJgIuOx2LTjJyK7lQRskqThDGIVyQRRoCc03jAfg2y0SVOJg61Fjv/i8rFuAO/StEnmbf0IHoM0J5U5HLYjM3b0bQYcNPrzcyqpdWRXoWjY+inLfIfCjab2D9npu4NAEibstQk39cOPeqJs1B+cVLDEpo0wjegN9YfusUCZAaRYj8Y+siNUv7Z5MwQEFL/6xZkv47cB2HQvSDl7UoStZ8CW7av99XyXGw/v0HFOs2tWXXfWXjU4a/Bm7vRS57+RoaNLy9DCjzpmEnKB18Pk+4Ey4u46nI+yfn/XH54R05dUaQcz7ZrxL1tRnz2zBf6nTBd9cgBcLfojgrGdf2U5cYEd4FinHgZAX41BlXlzR9U3SdAGyeHaOzHkEEldUFOisa33Hd5/3x7dA0fh/ugtCbzx6SjntcJWauRFdEynV7GXl4WPR0EIZYm8f07JNSMWlnHDMMshkItKahV6k7zsAloNr6o4nuWoZD5Oout0gHO/ohe3RAeIF9XniarO9SQ0+tIL/aCxong2RxBFcyItlbW9ad9diXZNrn2KzXIt5XMmr2AKeHQ4nU5SeJUZZpB2UNJceG3BTCOZvXoqZnywu1yvanKKyb1+52f6xSGtYviPOn3W4MrahbnM3/TuQrqs9E9hirovW15VA5yTTFyhAb6x
  template:
    metadata:
      creationTimestamp: null
      name: favouritecuisine
      namespace: hello-world
