apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - controller.yaml
  - ingress-frontend.yaml
  - ingress-hello-world.yaml
  - ingress-kratos.yaml
  - ingress-workspace-service.yaml
patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-dns.yaml
