apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../production
patchesStrategicMerge:
  - cert-manager.yaml
  - ingress.yaml
  - hello-world.yaml
  - frontend.yaml
  - kratos.yaml
  - workspace-service.yaml
