apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: hello-world
spec:
  encryptedData:
    favouritecuisine: AgBhIds425EST8AT1Lp8q3Czop/UI1ZrY59LIGHeDKNKPkKKFs4RCbtCZI4kHNdrYy4fUr4Kqx+yeMttmdc34Mz1dbv2k3YdqUk8DApfLfkXfUHrHPw0ih7Ok7gmo50lktb0hz6xID9cNVlyb3Xy2vUTH/1h7hGcNRe3NiGqT0dX9b2uqyMtxXxiewXDSfP1yCDUT6ktxHLpvsYvrcXPskF/4hYAEdcmlwz2dm8x263C4uOLU4JjN9A5m8i5Xpsqtm30TwPJzGtsYsRphpAH2zb5q9OMJFwZeFHjyv+QdF/S6vdNHnsH3I3fex2Dc1t9hEXi5R4I9ZD5ZPLTHJmNYtV4AoyCntNI8nppv4RKbJIABhKShdeUrUJgVfCyDerrPqy4ttItBL7LwyvCjHq5EGYgDtobDjcu/Vgdp8BNJSVSzn6uCb91pXN1WfvFJA1NDMpasMvNIN/FrXkTdSbQomRl51PqDuwIEgHfTtlXjKwJXbLCEbSmnzoC9+m7ZL+Y2Y89sJdsGYtMWSQUGaOx1yHntPPmZ2UDO+tDllPM0iwUiH7PZVnuuzltJX2FZOjbyoqX67+VEeDcRTlexNKUVCJxtcxj4hp7c1kd7ge8HOYW+yMU+2dSPEkrODeHRQ+oEAvoVPIINcJPp3/YLBRCXjDMP0Em4imuG112s14j0lqsalWJzjeU6duvtaZ3U6C4w7BouFlMX+I=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: hello-world

