name: hello-world

on:
  pull_request:
    branches:
      - master
    paths:
      - hello-world/**
      - .github/workflows/hello-world.yml

env:
  IMAGE: fnhsproduction.azurecr.io/platform/hello-world

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: platform
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Build & Push image"
        run: |
          cd platform/hello-world
          make docker-build
          make docker-push
