name: infrastructure

on:
  push:
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Terraform format
        run: terraform fmt -recursive -check
        working-directory: infrastructure
      - name: Validate Terraform of dev environment
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: infrastructure/environments/dev
      - name: Validate Terraform of production environment
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: infrastructure/environments/production
