name: Linting

on: [push]

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.6"
      - name: Installing shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - name: Run shfmt
        run: shfmt -d .
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hello-world
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run rustfmt
        working-directory: futurenhs-platform/hello-world
        run: cargo fmt
  rust2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
#      - uses: hecrj/setup-rust-action@v1
#        with:
#          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          cd hello-world
          cargo fmt
