name: Linting

on:
  push:
    paths:
      - *

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Installing shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - name: Run shfmt
        run: shfmt -d .
      - name: List files
        run: ls -a
      - name: Get path
        run: pwd
