name: Linting

on: [push]

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.6"
      - name: Installing shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - name: Run shfmt
        run: shfmt -d .
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run rustfmt
        run: |
          cd hello-world
          cargo fmt -- --check
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - name: Install modules
        working-directory: futurenhs-platform/frontend
        run: yarn
      - name: Run ESLint
        working-directory: futurenhs-platform/frontend
        run: yarn eslint . --ext .js,.ts,.tsx
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - name: Install modules
        working-directory: futurenhs-platform/frontend
        run: yarn
      - name: Run Prettier
        working-directory: futurenhs-platform/frontend
        run: yarn prettier --check "**/*.{js,ts,tsx,md,yaml,graphql}"
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      - name: Run Terraform fmt
        run: |
          cd futurenhs-platform/infrastructure
          terraform fmt -recursive -check
