name: workspace-service-master

on:
  push:
    branches:
      - master
    paths:
      - workspace-service/**
      - event-models/**
      - infrastructure/dev-overlay-variables.json
      - .github/workflows/workspace-service-master.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Make toolchain version available in current directory
        run: cp futurenhs-platform/rust-toolchain .
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
      - name: Cache sqlx
        id: cache-sqlx
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/sqlx
            ~/.cargo/bin/cargo-sqlx
          key: sqlx-0.1.0-beta.1
      - name: Install sqlx
        if: steps.cache-sqlx.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/frigus02/sqlx --rev 106a6a83952bfc0e3316d54f99d865e469dcc15a sqlx-cli
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            futurenhs-platform/workspace-service/target
          key: cargo-${{ hashFiles('futurenhs-platform/workspace-service/Cargo.lock') }}
      - name: Build
        working-directory: futurenhs-platform/workspace-service
        run: |
          set -e
          export DATABASE_URL=postgres://postgres:postgres@localhost:5432
          sqlx migrate run
          cargo sqlx prepare --check -- --release --bin workspace_service
          export SQLX_OFFLINE=true
          cargo clippy --release -- -D warnings
          cargo build --release
          export TEST_DATABASE_URL=$DATABASE_URL
          cargo test --release
      - name: Build & push image
        working-directory: futurenhs-platform/workspace-service
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          make docker-build tag=${TAG}
          make docker-push tag=${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/workspace-service:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST
      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Copy manifests
        run: |
          set -eux
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/workspace-service
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/workspace-service/manifests/* $GITHUB_WORKSPACE/futurenhs-deployments/workspace-service

      - name: Update image tag and deploy
        run: |
          set -eux

          cd $HOME
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          cd $GITHUB_WORKSPACE/futurenhs-deployments/workspace-service/base

          $HOME/kustomize edit set image $DIGEST

          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"

          git add -A
          git diff-index --quiet HEAD || git commit -am "CI: Update production image for ${TAG}"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            git push && break
            n+=1
            git pull --rebase
          done

          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi
